alerts:
  thresholds:
    bluetooth:
      rssi_min: -75
    imu:
      accel_max: 9.8
    wifi:
      rssi_min: -70
bluetooth:
  interval: 4.4
imu:
  interval: 5.5
llm:
  model: llama3.2:latest
wifi:
  interval: 3.3
